### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by kylematoba**
@andrewcalvano as discussed: a simple pagination example in the 'browse puzzles' page (still need to get the form to submit the puzzle title working).

### CODE REVIEW

**Comment by vr2262** [comment]
Is this ready to be merged? I'm not sure that the title part works. Plus, I think there's a steep price attached :dollar:

**Comment by kylematoba** [comment]
sorry, I discussed with Andrew in private. I guess it's meant more to show how it works than be directly merged. it's ugly, I'm still pretty clueless about flask :P

**Comment by vr2262** [comment]
No worries. I think there's a way to mark this as "not ready to be merged."

**Review by vr2262 — CHANGES_REQUESTED** [review]
Not ready to be merged.

**Comment by kylematoba** [comment]
Cool, thanks Viktor! It won't break anything, but I agree, it's not ready
to be merged.

**Comment by andrewcalvano** [comment]
Finished this feature.

**Comment by andrewcalvano** [comment]
Corrected last outstanding items, and ready to merge.

**Pull request merged**
